
export const RECEIVE_CLIENT = 'CLIENTS/RECEIVE_CLIENT'
export const RECEIVE_CLIENTS = 'CLIENTS/RECEIVE_CLIENTS'
export const SET_CREATING_CLIENT = 'CLIENTS/SET_CREATING_CLIENT'
export const SET_CREATING_CLIENT_ERROR = 'CLIENTS/SET_CREATING_CLIENT_ERROR'
export const CLEAR_CREATING_CLIENT_ERROR = 'CLIENTS/CLEAR_CREATING_CLIENT_ERROR'
export const SET_EDITING_CLIENT = 'CLIENTS/SET_EDITING_CLIENT'
export const SET_EDITING_CLIENT_ERROR = 'CLIENTS/SET_EDITING_CLIENT_ERROR'
export const CLEAR_EDITING_CLIENT_ERROR = 'CLIENTS/CLEAR_EDITING_CLIENT_ERROR'
