
export const RECEIVE_COMPANY = 'COMPANIES/RECEIVE_COMPANY'
export const RECEIVE_COMPANIES = 'COMPANIES/RECEIVE_COMPANIES'
export const SET_EDITING_COMPANY = 'COMPANIES/SET_EDITING_COMPANY'
export const SET_EDITING_COMPANY_ERROR = 'COMPANIES/SET_EDITING_COMPANY_ERROR'
export const CLEAR_EDITING_COMPANY_ERROR = 'COMPANIES/CLEAR_EDITING_COMPANY_ERROR'
