
export const SET_PAGE_ERRORS = 'GLOBAL/SET_PAGE_ERRORS'
export const SET_FLASH = 'GLOBAL/SET_FLASH'
export const CLEAR_FLASH = 'GLOBAL/CLEAR_FLASH'
export const SET_HEADER_TITLE = 'GLOBAL/SET_HEADER_TITLE'
export const SET_HEADER_BUTTONS = 'GLOBAL/SET_HEADER_BUTTONS'
