
export const RECEIVE_LAB = 'LABS/RECEIVE_LAB'
export const RECEIVE_LABS = 'LABS/RECEIVE_LABS'
export const SET_EDITING_LAB = 'LABS/SET_EDITING_LAB'
export const SET_EDITING_LAB_ERROR = 'LABS/SET_EDITING_LAB_ERROR'
export const CLEAR_EDITING_LAB_ERROR = 'LABS/CLEAR_EDITING_LAB_ERROR'
