
export const RECEIVE_PROJECT = 'PROJECTS/RECEIVE_PROJECT'
export const RECEIVE_PROJECTS = 'PROJECTS/RECEIVE_PROJECTS'
export const SET_CREATING_PROJECT = 'PROJECTS/SET_CREATING_PROJECT'
export const SET_CREATING_PROJECT_ERROR = 'PROJECTS/SET_CREATING_PROJECT_ERROR'
export const CLEAR_CREATING_PROJECT_ERROR = 'PROJECTS/CLEAR_CREATING_PROJECT_ERROR'
export const SET_EDITING_PROJECT = 'PROJECTS/SET_EDITING_PROJECT'
export const SET_EDITING_PROJECT_ERROR = 'PROJECTS/SET_EDITING_PROJECT_ERROR'
export const CLEAR_EDITING_PROJECT_ERROR = 'PROJECTS/CLEAR_EDITING_PROJECT_ERROR'
