
export const RECEIVE_SAMPLE = 'SAMPLES/RECEIVE_SAMPLE'
export const RECEIVE_SAMPLES = 'SAMPLES/RECEIVE_SAMPLES'
export const SET_EDITING_SAMPLE = 'SAMPLES/SET_EDITING_SAMPLE'
export const SET_EDITING_SAMPLE_ERROR = 'SAMPLES/SET_EDITING_SAMPLE_ERROR'
export const CLEAR_EDITING_SAMPLE_ERROR = 'SAMPLES/CLEAR_EDITING_SAMPLE_ERROR'

export const RECEIVE_GROUPED_SAMPLE_VALUES = 'SAMPLES/RECEIVE_GROUPED_SAMPLE_VALUES'
export const CLEAR_GROUPED_SAMPLE_VALUES = 'SAMPLES/CLEAR_GROUPED_SAMPLE_VALUES'
export const RECEIVE_SAMPLE_DATES = 'SAMPLES/RECEIVE_SAMPLE_DATES'
