
export const RECEIVE_SAMPLE_SCHEDULE = 'SITES/RECEIVE_SAMPLE_SCHEDULE'
export const RECEIVE_SAMPLE_SCHEDULES = 'SITES/RECEIVE_SAMPLE_SCHEDULES'
export const SET_CREATING_SAMPLE_SCHEDULE = 'SITES/SET_CREATING_SAMPLE_SCHEDULE'
export const SET_CREATING_SAMPLE_SCHEDULE_ERROR = 'SITES/SET_CREATING_SAMPLE_SCHEDULE_ERROR'
export const CLEAR_CREATING_SAMPLE_SCHEDULE_ERROR = 'SITES/CLEAR_CREATING_SAMPLE_SCHEDULE_ERROR'
export const SET_EDITING_SAMPLE_SCHEDULE = 'SITES/SET_EDITING_SAMPLE_SCHEDULE'
export const SET_EDITING_SAMPLE_SCHEDULE_ERROR = 'SITES/SET_EDITING_SAMPLE_SCHEDULE_ERROR'
export const CLEAR_EDITING_SAMPLE_SCHEDULE_ERROR = 'SITES/CLEAR_EDITING_SAMPLE_SCHEDULE_ERROR'
