
export const RECEIVE_SCHEDULE = 'SITES/RECEIVE_SCHEDULE'
export const RECEIVE_SCHEDULES = 'SITES/RECEIVE_SCHEDULES'
export const SET_CREATING_SCHEDULE = 'SITES/SET_CREATING_SCHEDULE'
export const SET_CREATING_SCHEDULE_ERROR = 'SITES/SET_CREATING_SCHEDULE_ERROR'
export const CLEAR_CREATING_SCHEDULE_ERROR = 'SITES/CLEAR_CREATING_SCHEDULE_ERROR'
export const SET_EDITING_SCHEDULE = 'SITES/SET_EDITING_SCHEDULE'
export const SET_EDITING_SCHEDULE_ERROR = 'SITES/SET_EDITING_SCHEDULE_ERROR'
export const CLEAR_EDITING_SCHEDULE_ERROR = 'SITES/CLEAR_EDITING_SCHEDULE_ERROR'
