
export const RECEIVE_SITE_DATA = 'SITES/RECEIVE_SITE_DATA'
export const RECEIVE_SITE_DATAS = 'SITES/RECEIVE_SITE_DATAS'
export const SET_CREATING_SITE_DATA = 'SITES/SET_CREATING_SITE_DATA'
export const SET_CREATING_SITE_DATA_ERROR = 'SITES/SET_CREATING_SITE_DATA_ERROR'
export const CLEAR_CREATING_SITE_DATA_ERROR = 'SITES/CLEAR_CREATING_SITE_DATA_ERROR'
export const SET_EDITING_SITE_DATA = 'SITES/SET_EDITING_SITE_DATA'
export const SET_EDITING_SITE_DATA_ERROR = 'SITES/SET_EDITING_SITE_DATA_ERROR'
export const CLEAR_EDITING_SITE_DATA_ERROR = 'SITES/CLEAR_EDITING_SITE_DATA_ERROR'
