
export const RECEIVE_SITE = 'LABS/RECEIVE_SITE'
export const RECEIVE_SITES = 'LABS/RECEIVE_SITES'
export const SET_EDITING_SITE = 'LABS/SET_EDITING_SITE'
export const SET_EDITING_SITE_ERROR = 'LABS/SET_EDITING_SITE_ERROR'
export const CLEAR_EDITING_SITE_ERROR = 'LABS/CLEAR_EDITING_SITE_ERROR'
