
export const RECEIVE_TEST = 'SAMPLES/RECEIVE_TEST'
export const RECEIVE_TESTS = 'SAMPLES/RECEIVE_TESTS'
export const SET_EDITING_TEST = 'SAMPLES/SET_EDITING_TEST'
export const SET_EDITING_TEST_ERROR = 'SAMPLES/SET_EDITING_TEST_ERROR'
export const CLEAR_EDITING_TEST_ERROR = 'SAMPLES/CLEAR_EDITING_TEST_ERROR'
