
export const RECEIVE_UPLOAD = 'UPLOADS/RECEIVE_UPLOAD'
export const RECEIVE_UPLOADS = 'UPLOADS/RECEIVE_UPLOADS'
export const REMOVE_UPLOAD = 'UPLOADS/REMOVE_UPLOAD'
export const SET_UPLOADING_ERROR = 'UPLOADS/SET_UPLOADING_ERROR'
export const CLEAR_UPLOADING_ERROR = 'UPLOADS/CLEAR_UPLOADING_ERROR'
