
export const RECEIVE_UPLOAD = 'UPLOADS/RECEIVE_UPLOAD'
export const RECEIVE_UPLOADS = 'UPLOADS/RECEIVE_UPLOADS'
export const REMOVE_UPLOAD = 'UPLOADS/REMOVE_UPLOAD'
export const SET_UPLOADING = 'UPLOADS/SET_UPLOADING'
