
export const RECEIVE_USER = 'USERS/RECEIVE_USER'
export const RECEIVE_USERS = 'USERS/RECEIVE_USERS'
export const REMOVE_USER = 'USERS/REMOVE_USER'

export const SET_CREATING_USER = 'USERS/SET_CREATING_USER'
export const SET_CREATING_USER_ERROR = 'USERS/SET_CREATING_USER_ERROR'
export const CLEAR_CREATING_USER_ERROR = 'USERS/CLEAR_CREATING_USER_ERROR'

export const SET_CURRENT_USER = 'USERS/SET_CURRENT_USER'

export const SET_SIGNIN_PROCESSING = 'USERS/SET_SIGNIN_PROCESSING'
export const SET_SIGNIN_ERROR = 'USERS/SET_SIGNIN_ERROR'
export const CLEAR_SIGNIN_ERROR = 'USERS/CLEAR_SIGNIN_ERROR'

export const SET_EDITING_USER = 'USERS/SET_EDITING_USER'
export const SET_EDITING_USER_ERROR = 'USERS/SET_EDITING_USER_ERROR'
export const CLEAR_EDITING_USER_ERROR = 'USERS/CLEAR_EDITING_USER_ERROR'

export const SET_ACCEPTING_INVITE = 'USERS/SET_ACCEPTING_INVITE'
export const SET_ACCEPT_INVITE_ERROR = 'USERS/SET_ACCEPT_INVITE_ERROR'
export const CLEAR_ACCEPT_INVITE_ERROR = 'USERS/CLEAR_ACCEPT_INVITE_ERROR'
